### PR TITLE
Instrument batchGet/batchWrite/transactGet/transactWrite

### LINKED ISSUE #83: dynamodb: batchGet, batchWrite, transactWrite, and transactGet are not tracked in database instrumentation
## Summary

Operations such as getItem and putItem are tracked for dynamodb, but batchGet, batchWrite, etc. are not tracked at all in the datastore tab

## Desired Behavior

Track the average duration and throughput of batchGet, batchWrite, transactWrite, and transactGet 

## Possible Solution

```patch
--- a/lib/dynamodb.js
+++ b/lib/dynamodb.js
@@ -20,6 +20,10 @@ const DOC_CLIENT_OPERATIONS = [
   'put',
   'update',
   'delete',
+  'batchGet',
+  'batchWrite',
+  'transactGet',
+  'transactWrite',
   'query',
   'scan'
 ]
```

It seems like the serviceClientOperationsMap required by `@newrelic/aws-sdk` is available in the latest aws-sdk - I haven't checked if older sdks are different

```js
// node_modules/aws-sdk/lib/dynamodb/document_client.js
  /**
   * @api private
   */
  serviceClientOperationsMap: {
    batchGet: 'batchGetItem',
    batchWrite: 'batchWriteItem',
    delete: 'deleteItem',
    get: 'getItem',
    put: 'putItem',
    query: 'query',
    scan: 'scan',
    update: 'updateItem',
    transactGet: 'transactGetItems',
    transactWrite: 'transactWriteItems'
  },

```

## Additional context

Providing this information gives us an accurate idea of the way an application and transaction uses batch writes and gets.

It seems as if uninstrumented API calls get reported as a call to `External service: dynamodb.us-east-1.amazonaws.com:443` in the external services tab instead

### PR DESCRIPTION
**Pull request by TysonAndre**
Fixes #83

## Proposed Release Notes

* Properly instrument dynamodb batchGet, batchWrite, transactGet, and transactGet calls as database operations instead of External service calls

## Details

```js
  batchGet: function(params, callback) {
    var operation = this.serviceClientOperationsMap['batchGet'];
    return this.makeServiceRequest(operation, params, callback);
  },
  batchWrite: function(params, callback) {
    var operation = this.serviceClientOperationsMap['batchWrite'];
    return this.makeServiceRequest(operation, params, callback);
  },
  transactWrite: function(params, callback) {
    var operation = this.serviceClientOperationsMap['transactWrite'];
    return this.makeServiceRequest(operation, params, callback);
  },
  transactGet: function(params, callback) {
    var operation = this.serviceClientOperationsMap['transactGet'];
    return this.makeServiceRequest(operation, params, callback);
  },
```

node_modules/aws-sdk/lib/dynamodb/document_client.js is not doing anything unusual in https://github.com/aws/aws-sdk-js/blob/master/lib/dynamodb/document_client.js#L205-L208 - the method call corresponds to a single service request (HTTP call)

And the oldest supported version from newrelic-aws-sdk 2.403.0 is also the same implementation and has all 4 operations
https://github.com/aws/aws-sdk-js/blob/v2.403.0/lib/dynamodb/document_client.js#L157-L476

### CODE REVIEW

**Comment by nijotz** [comment]
Weird, why would this cause a missing module error in the test?

> not ok 1 - Cannot find module 'antlr4/index' Require stack: - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/src/DynamoDbGrammarListener.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/src/CborSExprGenerator.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/src/Encoders.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/src/BaseOperations.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/generated-src/Operations.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/src/DaxClient.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/node_modules/amazon-dax-client/src/AmazonDaxClient.js - /home/runner/work/node-newrelic-aws-sdk/node-newrelic-aws-sdk/tests/versioned/amazon-dax-client.tap.js

Maybe dynamically loading modules?

**Comment by TysonAndre** [comment]
> Weird, why would this cause a missing module error in the test?

It isn't caused by my change, it was caused by new releases to external npm packages, very likely a new release of `antlr4` published to npm for the javascript sdk.

`versioned-tests` is the test runner used for this sdk. It will try to run the tests with as many combinations of minor(`--minor`) npm package versions installed as the configuration in tests/versioned/package.json allows


```
node-newrelic-aws-sdk ±dynamodb-batch » node_modules/.bin/versioned-tests --help                                          
Usage: versioned-tests [options] [test-globs...]

Options:
  -j, --jobs <n>                    Max parallel test executions [5] (default: 5)
  -i, --install <n>                 Max parallel installations [1] (default: 1)
  -p, --print <mode>                Specify print mode [pretty] (default: "pretty")
  -s, --skip <keyword>[,<keyword>]  Skip files containing the supplied keyword(s)
  --major                           Only iterate on major versions of packages.
  --minor                           Iterate over minor versions of packages (default).
  --patch                           Iterate over every patch version of packages.
  -h, --help                        output usage information
```

**Comment by TysonAndre** [comment]
https://github.com/newrelic/node-newrelic-aws-sdk/pull/84/checks?check_run_id=1560933609

I see that it updated dependencies and installed (or updated to) antlr4 4.9.0 anyway, possibly as a subdependency of amazon-dax-client from the error message for node 10. Not sure how to work around that.

**Comment by TysonAndre** [comment]
https://www.npmjs.com/package/amazon-dax-client/v/1.2.5#125 - If I change this to 1.2.5 it might work

> Lock antlr4 to 4.8.x to avoid breaking application running older node version when upgrading to 4.9.0

**Comment by nijotz** [comment]
Hmmm, I see. Ya, outside of being able to control sub-dependency versions through versioned-tests somehow, I don't see a way around this other than going with the newer version that locks antlr to "4.8.x". What a mess. Thanks for researching this. Relevant issue: https://github.com/antlr/antlr4/issues/2968

**Review by nijotz — APPROVED** [review]

**Pull request merged**
