### PR TITLE
Fix "Illegal return statement"

### PR DESCRIPTION
**Pull request by eitoball**
## Proposed Release Notes

* Fix "Uncaught SyntaxError: Illegal return statement".

## Details

`return` can only be inside functions. Fix this error, IIFE (Immediately-Invoked Function Expression).

### CODE REVIEW

**Comment by garbados** [comment]
Instead of an IIFE, why not use an else clause?

**Comment by eitoball** [comment]
@garbados Changed to use `if-else`.

**Review by jordigh — APPROVED** [review]
lgtm, how did the return statement ever work?

**Review by bizob2828 — CHANGES_REQUESTED** [review]
@eitoball can you explain where you're seeing the syntax error?  I'm going to assume it's in some linter but I'd ask why it's linting code that is not yours

There's missing context when just looking at this file but I'll try to explain.  Basically this file gets used when you run `require('@newrelic/aws-sdk')` or `node -r @newrelic/aws-sdk /path/to/program`.  This will flow through Node.js module loading system and in the CommonJS(CJS) loader wraps the code in a function [here](https://github.com/nodejs/node/blob/master/lib/internal/modules/cjs/loader.js#L1105).  That's why the return works just fine.  I'm hesitant to merge this PR as it does not really address any issue for the package.

**Pull request closed without merging**
